"""Writeback #2's payload: deterministic, mergeable compatibility code.

Templates guarantee valid dbt SQL for the supported change classes
(rename / removal / logic change); the LLM narrates impact but never
authors the merged code (ADR-0002). Anything a template can't map cleanly
is flagged `requires_human`.
"""
from __future__ import annotations

import textwrap

from agent.models import CompatArtifact, ModelChange

HEADER = """\
-- Generated by Downstream Impact Guardian.
-- Purpose: preserve the pre-PR contract of `{model}` for downstream
-- consumers while they migrate. Safe to merge as-is; delete once every
-- consumer found in DataHub lineage has moved off the old shape.
"""


def generate_compat_view(change: ModelChange) -> CompatArtifact | None:
    """Schema change -> a `<model>_compat` view exposing the OLD columns."""
    if "schema" not in change.kinds or not change.old_columns:
        return None

    renamed = dict(change.renames)                       # old -> new
    removed = {c.name for c in change.columns if c.change == "removed"}
    unmapped = removed - set(renamed)
    requires_human = bool(unmapped)

    exprs: list[tuple[str, str]] = []  # (select expression, trailing comment)
    for col in change.old_columns:
        if col in renamed:
            exprs.append((f"{renamed[col]} as {col}", ""))
        elif col in unmapped:
            exprs.append((f"cast(null as string) as {col}",
                          "removed upstream: NO automatic mapping, fix me"))
        else:
            exprs.append((col, ""))
    lines = []
    for i, (expr, comment) in enumerate(exprs):
        s = expr + ("" if i == len(exprs) - 1 else ",")
        if comment:
            s += "  -- " + comment
        lines.append("    " + s)

    view_name = f"{change.model_name}_compat"
    sql = (HEADER.format(model=change.model_name)
           + "{{ config(materialized='view') }}\n\nselect\n"
           + "\n".join(lines)
           + f"\nfrom {{{{ ref('{change.model_name}') }}}}\n")

    yml = textwrap.dedent(f"""\
        version: 2

        models:
          - name: {view_name}
            description: >
              Backward-compatibility view generated by Downstream Impact
              Guardian. Exposes the pre-change contract of {change.model_name}.
            columns:
        """)
    for old, _ in change.renames:
        yml += (f"      - name: {old}\n"
                f"        description: Preserved from the old contract.\n"
                f"        tests: [not_null]\n")

    return CompatArtifact(view_name=view_name, sql=sql, schema_yml=yml,
                          requires_human=requires_human,
                          for_model=change.model_name)


def generate_legacy_view(change: ModelChange,
                         compat_views: dict[str, str]) -> CompatArtifact | None:
    """Logic-only change, or a DELETED model -> a `<model>_legacy` view
    carrying the OLD SQL, so consumers keep a working relation. If an
    upstream model got a compat view in the same PR, retarget refs at it so
    the legacy SQL still compiles."""
    is_removed = "removed" in change.kinds
    is_logic_only = "logic" in change.kinds and "schema" not in change.kinds
    if not (is_removed or is_logic_only) or not change.old_sql.strip():
        return None
    old_sql = change.old_sql
    for model, compat in compat_views.items():
        old_sql = old_sql.replace(f"ref('{model}')", f"ref('{compat}')")

    view_name = f"{change.model_name}_legacy"
    why = ("this PR DELETES the model; consumers need a relation to migrate "
           "from" if is_removed else
           "consumers pinned to the old metric definition keep a working ref")
    sql = (HEADER.format(model=change.model_name)
           + "{{ config(materialized='view') }}\n\n"
           + old_sql.strip() + "\n")
    yml = textwrap.dedent(f"""\
        version: 2

        models:
          - name: {view_name}
            description: >
              Pre-PR definition of {change.model_name}, preserved verbatim
              by Downstream Impact Guardian — {why}.
        """)
    return CompatArtifact(view_name=view_name, sql=sql, schema_yml=yml,
                          for_model=change.model_name)


def generate_all(changes: list[ModelChange]) -> list[CompatArtifact]:
    artifacts: list[CompatArtifact] = []
    retarget: dict[str, str] = {}
    for ch in changes:
        art = generate_compat_view(ch)
        if art:
            artifacts.append(art)
            retarget[ch.model_name] = art.view_name
    # Deleted upstreams must be retargeted too: a legacy view whose SQL
    # refs a model this same PR deletes would fail dbt build. Register all
    # legacy names BEFORE rendering (cascading deletions).
    for ch in changes:
        if "removed" in ch.kinds and ch.old_sql.strip():
            retarget[ch.model_name] = f"{ch.model_name}_legacy"
    for ch in changes:
        art = generate_legacy_view(ch, {m: v for m, v in retarget.items()
                                        if m != ch.model_name})
        if art:
            artifacts.append(art)
    return artifacts
